var data_mmg = [
	{ name: "Hollywood Salad", source: "Muscle Maker Grill", category: "Lighter Side", fat: 17, carbs: 4, protein: 33, calories: 302 },
	{ name: "Champion Pasta", source: "Muscle Maker Grill", category: "Lighter Side", fat: 6, carbs: 53, protein: 25, calories: 374 },
	{ name: "Mona Lisa Wrap", source: "Muscle Maker Grill", category: "Lighter Side", fat: 17, carbs: 30, protein: 38, calories: 368 },
	{ name: "Penne Romano", source: "Muscle Maker Grill", category: "Lighter Side", fat: 4.5, carbs: 42, protein: 36, calories: 367 },
	{ name: "Tucson", source: "Muscle Maker Grill", category: "Lighter Side", fat: 11, carbs: 44, protein: 27, calories: 391 },

	{ name: "Texas Chicken Nuggets", source: "Muscle Maker Grill", category: "Warm Ups", fat: 6, carbs: 13, protein: 43, calories: 289 },
	{ name: "Honey BBQ Nuggets", source: "Muscle Maker Grill", category: "Warm Ups", fat: 6, carbs: 13, protein: 43, calories: 297 },
	{ name: "Teriyaki Chicken Nuggets", source: "Muscle Maker Grill", category: "Warm Ups", fat: 4, carbs: 14, protein: 44, calories: 285 },
	{ name: "Loaded Baked Potato", source: "Muscle Maker Grill", category: "Warm Ups", fat: 4, carbs: 38, protein: 7, calories: 209 },
	{ name: "Edamame", source: "Muscle Maker Grill", category: "Warm Ups", fat: 5, carbs: 10, protein: 11, calories: 121 },
	{ name: "Turkey Chili Cup", source: "Muscle Maker Grill", category: "Warm Ups", fat: 10, carbs: 38, protein: 23, calories: 337 },

	{ name: "Italiano Salad with Grilled Chicken", source: "Muscle Maker Grill", category: "Fit Salads", fat: 13, carbs: 17, protein: 48, calories: 395 },
	{ name: "Muscle Maker Caesar Salad", source: "Muscle Maker Grill", category: "Fit Salads", fat: 20, carbs: 4, protein: 3, calories: 200 },
	{ name: "Mardi Gras Cajun Grilled Chicken Salad", source: "Muscle Maker Grill", category: "Fit Salads", fat: 29, carbs: 8, protein: 37, calories: 447 },
	{ name: "Lean & Mean Cheeseburger Salad", source: "Muscle Maker Grill", category: "Fit Salads", fat: 42, carbs: 27, protein: 41, calories: 658 },
	{ name: "Turkey Taco Salad", source: "Muscle Maker Grill", category: "Fit Salads", fat: 26, carbs: 16, protein: 55, calories: 523 },

	{ name: "MMG Signature Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 28, carbs: 53, protein: 46, calories: 651 },
	{ name: "Rocky Balboa Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 25, carbs: 66, protein: 59, calories: 747 },
	{ name: "BBQ Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 18, carbs: 70, protein: 64, calories: 716 },
	{ name: "Low Carb Caesar Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 31, carbs: 51, protein: 45, calories: 670 },
	{ name: "European Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 12, carbs: 56, protein: 49, calories: 542 },
	{ name: "Yee-ha! Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 30, carbs: 66, protein: 35, calories: 679 },
	{ name: "Santa Fe Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 35, carbs: 77, protein: 42, calories: 788 },
	{ name: "XXL Turkey Burger Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 28, carbs: 64, protein: 36, calories: 598 },
	{ name: "Turkey meatball Parmesan Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 29, carbs: 74, protein: 47, calories: 762 },
	{ name: "Tex-Mex Fajita Wrap", source: "Muscle Maker Grill", category: "Muscle Maker Wraps", fat: 16, carbs: 60, protein: 49, calories: 607 },

	{ name: "Chicken Breast Signature Sandwich", source: "Muscle Maker Grill", category: "Sandwiches", fat: 24, carbs: 39, protein: 51, calories: 572 },
	{ name: "Premium Burger Signature Sandwich", source: "Muscle Maker Grill", category: "Sandwiches", fat: 34, carbs: 39, protein: 51, calories: 665 },

	{ name: "Vegetarian Italiano Salad", source: "Muscle Maker Grill", category: "Vegetarian", fat: 9, carbs: 17, protein: 14, calories: 213 },
	{ name: "Veggie Wrap", source: "Muscle Maker Grill", category: "Vegetarian", fat: 13, carbs: 64, protein: 20, calories: 449 },
	{ name: "Penne with Marinara Sauce", source: "Muscle Maker Grill", category: "Vegetarian", fat: 25, carbs: 66, protein: 13, calories: 343 },
	{ name: "Brown Rice & Beans", source: "Muscle Maker Grill", category: "Vegetarian", fat: 2, carbs: 55, protein: 6, calories: 261 },
	{ name: "Edamame", source: "Muscle Maker Grill", category: "Vegetarian", fat: 5, carbs: 10, protein: 11, calories: 121 },

	{ name: "Cajun Chicken & Penne", source: "Muscle Maker Grill", category: "Power Pasta", fat: 10, carbs: 87, protein: 50, calories: 675 },
	{ name: "Penne & Reduced Fat Vodka Sauce with Chicken", source: "Muscle Maker Grill", category: "Power Pasta", fat: 8, carbs: 71, protein: 58, calories: 608 },
	{ name: "Sesame Chicken Teriyaki Pasta", source: "Muscle Maker Grill", category: "Power Pasta", fat: 12, carbs: 82, protein: 67, calories: 740 },

	{ name: "El Mexicana", source: "Muscle Maker Grill", category: "Guiltless Entrees", fat: 8, carbs: 56, protein: 45, calories: 484 },
	{ name: "Turkey Chili", source: "Muscle Maker Grill", category: "Guiltless Entrees", fat: 22, carbs: 81, protein: 49, calories: 725 },
	{ name: "Teriyaki Grilled Chicken Stir-Fry", source: "Muscle Maker Grill", category: "Guiltless Entrees", fat: 11, carbs: 97, protein: 54, calories: 724 },
	{ name: "Arizona", source: "Muscle Maker Grill", category: "Guiltless Entrees", fat: 25, carbs: 49, protein: 41, calories: 596 },

	{ name: "Godfather", source: "Muscle Maker Grill", category: "Low Carb Solutions", fat: 12, carbs: 17, protein: 60, calories: 429 },
	{ name: "Tuscany", source: "Muscle Maker Grill", category: "Low Carb Solutions", fat: 25, carbs: 8, protein: 50, calories: 451 },
	{ name: "Texas", source: "Muscle Maker Grill", category: "Low Carb Solutions", fat: 10, carbs: 25, protein: 49, calories: 391 },

	{ name: "Turkey Meatballs", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 8, carbs: 32, protein: 29, calories: 325 },
	{ name: "Pastsa Salad", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 3, carbs: 43, protein: 8, calories: 237 },
	{ name: "Steamed Broccoli", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 0, carbs: 5, protein: 2, calories: 24 },
	{ name: "Cucumber Salad", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 0, carbs: 8, protein: 1, calories: 36 },
	{ name: "Brown Rice", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 3, carbs: 68, protein: 8, calories: 329 },
	{ name: "Baked Potato", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 0, carbs: 32, protein: 4, calories: 142 },
	{ name: "Western Potatoes", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 0, carbs: 32, protein: 3, calories: 138 },
	{ name: "Caesar Salad", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 4, carbs: 2, protein: 1.5, calories: 53 },
	{ name: "Brown Rice & Beans", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 2, carbs: 50, protein: 8, calories: 261 },
	{ name: "Savory Spinach", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 8, carbs: 5, protein: 4, calories: 95 },
	{ name: "Sweet Potato Fries", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 10, carbs: 31, protein: 2, calories: 243 },
	{ name: "Guacamole", source: "Muscle Maker Grill", category: "Extras", combo: "Muscle Maker Wraps", fat: 8, carbs: 5, protein: 1, calories: 91 },
	{ name: "Fresh Fish (Tilapia)", source: "Muscle Maker Grill", category: "Extras", fat: 6, carbs: 0, protein: 59, calories: 290 },
	{ name: "Fresh Shrimp", source: "Muscle Maker Grill", category: "Extras", fat: 3, carbs: 1, protein: 33, calories: 173 },
	{ name: "USDA Steak", source: "Muscle Maker Grill", category: "Extras", fat: 9, carbs: 6, protein: 34, calories: 282 },
	{ name: "Grilled Chicken Breast", source: "Muscle Maker Grill", category: "Extras", fat: 6, carbs: 0, protein: 53, calories: 281 },

	{ name: "Chocolate Peanut Butter Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 11, carbs: 27, protein: 44, calories: 390 },
	{ name: "Fresh Strawberry Banana Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 2, carbs: 53, protein: 43, calories: 392 },
	{ name: "Chocolate Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 3, carbs: 23, protein: 41, calories: 280 },
	{ name: "Vanilla Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 2, carbs: 24, protein: 42, calories: 280 },
	{ name: "Strawberry Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 2, carbs: 24, protein: 42, calories: 280 },
	{ name: "Snappy Apple Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 2, carbs: 80, protein: 42, calories: 390 },
	{ name: "Chocolate Banana Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 3, carbs: 53, protein: 42, calories: 392 },
	{ name: "Tropical Paradise Shake", source: "Muscle Maker Grill", category: "Big Protein Shakes", fat: 2, carbs: 50, protein: 43, calories: 350 }
];
